steps:
  # Build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "us-central1-docker.pkg.dev/$PROJECT_ID/gcp-poc-demo-ar", "."]

  # Push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "us-central1-docker.pkg.dev/$PROJECT_ID/gcp-poc-demo-ar"]

  # Deploy container image to GKE
# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=gke.yaml
#   - --image=gcr.io/$PROJECT_ID/gcpdemo
#   - --location=us-central1-c
#   - --cluster=gcp-poc-demo
#   - --namespace=gcp-poc-demo
